name: Build Sample App

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install NDK 21
      run: echo "y" | sudo /usr/local/lib/android/sdk/tools/bin/sdkmanager --install "ndk;21.0.6113669" "ndk;20.0.5594570" --sdk_root=${ANDROID_SDK_ROOT}
    - name: Build with Gradle
      run: ./gradlew :sample:assembleDebug :tutorial:assembleDebug
    - name: upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: sample-app.apk
        path: android/sample/build/outputs/apk/debug/sample-debug.apk
